apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
      - name: server
        image: ghcr.io/immich-app/immich-server:release
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2283
        env:
        - name: DB_HOSTNAME
          value: immich-postgres
        - name: DB_USERNAME
          value: immich
        - name: DB_PASSWORD
          value: immich123
        - name: DB_DATABASE_NAME
          value: immich
        - name: REDIS_HOSTNAME
          value: immich-redis
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://immich-ml:3003
        volumeMounts:
        - name: photos
          mountPath: /usr/src/app/upload
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: immich-photos-pvc

