spec:
  project: default
  source:
    repoURL: https://github.com/itechboss/homelab-k8s.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

